### ISSUE TITLE
Override app files using docker-compose

### ISSUE THREAD

**Issue by ThorstenHans** [fabianwilliams/bsed#2]
Once you've all your images in place, you can also use docker-compose to override app sources without having the requirement to rebuild the image

**Comment by fabianwilliams-zz** [comment]
Thanks @ThorstenHans yep, i saw that oversight and it is remedied now. Cheers buddy

**Comment by fabianwilliams-zz** [comment]
Actually I wanted to show the ability to build you own custom image v/s using my image on docker hub. the build is not needed if you use my image ofcourse but if you want to use my source code and possibly modify it and create your own custom image you will need the build command @ThorstenHans Ill clarify this in the Readme.md file when i get it ready. but thanks for calling it out
